/**
 * header-v2 Block
 * Generated by NxPlatform Migration Tool
 */

export default function decorate(block) {
  // Get block configuration
  const config = readBlockConfig(block);

  // Process rows and cells
  const rows = [...block.children];

  rows.forEach((row, index) => {
    const cells = [...row.children];

    cells.forEach((cell, cellIndex) => {
      // Add semantic classes based on field mapping
      const fieldName = getFieldName(index, cellIndex);
      if (fieldName) {
        cell.classList.add(fieldName);
      }

      // Process images
      processImages(cell);

      // Process links
      processLinks(cell);
    });
  });

  // Add block-specific initialization
  initializeBlock(block, config);
}

/**
 * Read block configuration from data attributes
 */
function readBlockConfig(block) {
  const config = {};
  [...block.querySelectorAll(':scope > div > div')].forEach((cell) => {
    const key = cell.textContent?.trim().toLowerCase().replace(/\s+/g, '-');
    const value = cell.nextElementSibling?.textContent?.trim();
    if (key && value) {
      config[key] = value;
    }
  });
  return config;
}

/**
 * Map row/cell index to field name
 */
function getFieldName(rowIndex, cellIndex) {
  const fieldMap = {
    '0-0': 'jcr:primaryType',
    '0-1': 'sling:resourceType',
    '1-0': 'anchorID',
    '1-1': 'atsLastModifiedBy',
    '2-0': 'atsLastModifiedOn',
    '2-1': 'backToTopInteractionId',
    '3-0': 'customCssClasses',
    '3-1': 'eyebrowLinks',
    '4-0': 'floatingisidesktop',
    '4-1': 'floatingisimobile',
    '5-0': 'floatingisitext',
    '5-1': 'headerType',
    '6-0': 'l10Title',
    '6-1': 'loginCloseLinkIcon',
    '7-0': 'loginL10Title',
    '7-1': 'loginOpenLinkIcon',
    '8-0': 'loginSectionTitle',
    '8-1': 'logoutCloseLinkIcon',
    '9-0': 'logoutOpenLinkIcon',
    '9-1': 'pageInteractionId',
    '10-0': 'primaryNavMenuItems',
    '10-1': 'sectionTitle',
    '11-0': 'skipToMainContent',
    '11-1': 'stickyScrollType',
    '12-0': 'textIsRich',
    '12-1': 'utilityNavMenuItems',
    '13-0': 'welcomeText'
  };
  return fieldMap[`${rowIndex}-${cellIndex}`];
}

/**
 * Process images in a cell
 */
function processImages(cell) {
  const images = cell.querySelectorAll('img');
  images.forEach((img) => {
    // Add lazy loading
    img.loading = 'lazy';

    // Wrap in picture element if not already
    if (img.parentElement.tagName !== 'PICTURE') {
      const picture = document.createElement('picture');
      img.parentElement.insertBefore(picture, img);
      picture.appendChild(img);
    }
  });
}

/**
 * Process links in a cell
 */
function processLinks(cell) {
  const links = cell.querySelectorAll('a');
  links.forEach((link) => {
    // Add target blank for external links
    if (link.hostname !== window.location.hostname) {
      link.target = '_blank';
      link.rel = 'noopener noreferrer';
    }
  });
}

/**
 * Initialize block functionality
 */
function initializeBlock(block, config) {
  // Add loaded class for CSS transitions
  block.classList.add('loaded');

  // Dispatch custom event for extensibility
  block.dispatchEvent(new CustomEvent('block:loaded', {
    detail: { config },
    bubbles: true,
  }));
}
